<<<<<<< HEAD
@extends('layouts.app') 
 @section('content')
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            
        </h2>
    </x-slot>
     
    <div id="show"></div>

       <script src="{{asset('js/app.js')}}" ></script>

   <p>Show post here </p>

@endsection  
=======
@extends('layouts.app')
@section('content')

<div>
  
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
  <g>
    <circle cx="60" cy="50" r="4" fill="#e15b64">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.67s"></animate>
      <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.67s"></animate>
    </circle>
    <circle cx="60" cy="50" r="4" fill="#e15b64">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.33s"></animate>
      <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.33s"></animate>
    </circle>
    <circle cx="60" cy="50" r="4" fill="#e15b64">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="0s"></animate>
      <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="0s"></animate>
    </circle>
  </g><g transform="translate(-15 0)">
    <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#f8b26a" transform="rotate(90 50 50)"></path>
    <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#f8b26a">
      <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform>
    </path>
    <path d="M50 50L20 50A30 30 0 0 1 80 50Z" fill="#f8b26a">
      <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;-45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform>
    </path>
  </g>
  <!-- [ldio] generated by https://loading.io/ --></svg>
</div>
<div class="py-12">
    <div class="max-w-xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
          
          
        <script src="{{asset('js/app.js')}}"></script>
        </div>
    </div>
</div>
@endsection
    



   

   
 
>>>>>>> b329453e601d3261a7d5ffd7f04845ab2cd8d1a6
